In [1]:
from sklearn.datasets import load_iris
import pandas as pd

In [2]:
df=load_iris()
dir(df)
df.data
df.feature_names
df1=pd.DataFrame(df.data,columns=df.feature_names)
df2=pd.DataFrame(df.target,columns=['target'])
df1['target']=df2['target']
df1.to_csv('G:/dataset/classification/iris.csv')

In [3]:
df3=pd.read_csv('G:/dataset/classification/iris.csv')
df3

,Unnamed: 0,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,0,5.1,3.5,1.4,0.2,0
1,1,4.9,3.0,1.4,0.2,0
2,2,4.7,3.2,1.3,0.2,0
3,3,4.6,3.1,1.5,0.2,0
4,4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...,...
145,145,6.7,3.0,5.2,2.3,2
146,146,6.3,2.5,5.0,1.9,2
147,147,6.5,3.0,5.2,2.0,2
148,148,6.2,3.4,5.4,2.3,2
149,149,5.9,3.0,5.1,1.8,2